modLoader="javafml"
loaderVersion="[34,)"
license="MIT"

[[mods]]
modId="passablefoliage"
version="${file.jarVersion}"
displayName="Passable Foliage"
authors="Snownee"
displayURL="https://minecraft.curseforge.com/projects/passable-foliage"
description="Remove collision from leaves"
